# Generated by Django 6.1 on 2026-08-29 00:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('lecture_date', models.DateField()),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('summary_due_at', models.DateTimeField(blank=True, null=True)),
                ('summary_text', models.TextField(blank=True)),
                ('summary_written_at', models.DateTimeField(blank=True, null=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_summary_generated_at', models.DateTimeField(blank=True, null=True)),
                ('ai_summary_hidden', models.BooleanField(default=False)),
                ('ai_summary_stale', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('client_updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('pg_created_at', models.DateTimeField(auto_now_add=True)),
                ('pg_modified_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'entries',
                'ordering': ['-lecture_date', '-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=300)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('user', 'User'), ('ai', 'AI')], default='user', max_length=20)),
                ('snoozed_until', models.DateField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('client_updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('pg_created_at', models.DateTimeField(auto_now_add=True)),
                ('pg_modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='notes.entry')),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=300)),
                ('suggested_due', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('saved', 'Saved'), ('skipped', 'Skipped'), ('duplicate', 'Duplicate')], default='new', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('pg_created_at', models.DateTimeField(auto_now_add=True)),
                ('pg_modified_at', models.DateTimeField(auto_now=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='notes.entry')),
            ],
            options={
                'ordering': ['pg_created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['user', '-lecture_date'], name='notes_entry_user_id_4710ea_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['user', 'summary_due_at'], name='notes_entry_user_id_2a0c32_idx'),
        ),
    ]
